# Simple overwrite standard Sulu image proxy path
pb_sulu_storage.website.image.proxy:
    path: %sulu_media.format_cache.media_proxy_path%
    defaults:
        _controller: PBSuluStorageBundle:MediaStream:getImage
        _requestAnalyzer: false
    requirements:
        slug: .*

# Simple overwrite standard Sulu download path
pb_sulu_storage.website.media.download:
    path: "%sulu_media.media_manager.media_download_path%"
    defaults:
        _controller: PBSuluStorageBundle:MediaStream:download
        _requestAnalyzer: false
    requirements:
        slug: .*
