services:
    # Path resolvers
    pb_sulu_storage.local.path_resolver:
        class: PB\Bundle\SuluStorageBundle\Resolver\LocalPathResolver
        tags:
            - { name: pb_sulu_storage.path_resolver, alias: local }
        calls:
            - ['setAbsolutePathPrefix', ['%kernel.root_dir%/../web']]

    pb_sulu_storage.s3.path_resolver:
        class: PB\Bundle\SuluStorageBundle\Resolver\AwsS3v3PathResolver
        tags:
            - { name: pb_sulu_storage.path_resolver, alias: awss3v3 }

    # External URL resolvers
    pb_sulu_storage.s3.external_url_resolver:
        class: PB\Bundle\SuluStorageBundle\Resolver\AwsS3v3ExternalUrlResolver
        tags:
            - { name: pb_sulu_storage.external_url_resolver, alias: awss3v3 }