sudo: false

language: php

php:
    - '5.6'
    - '7.3'

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - travis_retry composer selfupdate

before_script:
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.3" ]]; then wget https://github.com/infection/infection/releases/download/0.12.0/infection.phar; fi
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.3" ]]; then wget https://github.com/infection/infection/releases/download/0.12.0/infection.phar.asc; fi
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.3" ]]; then chmod +x infection.phar; fi
    - COMPOSER_MEMORY_LIMIT=-1 travis_wait composer install --dev --prefer-source

script:
    - ./vendor/bin/phpunit
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.3" ]]; then ./infection.phar --min-msi=95 --min-covered-msi=100 --threads=4; fi

env:
    global:
        - secure: bh8uxIPN4hMWkGwDN7RELuDqZz/emyeElM9lrEYLUhDk49vIL+AkiJF1TZNu6SLh/DG/ETGCxLK7Ns5sKRsdFj83DOxaVmW46egf75bAZnqFS7wv1aRgNet3tyNy6nyJzNUrXQEdJRyRG2bwFnx3/Vvvsg8YI/Wj5AQnsDQc/rvsqYfpye2rVOSAXT6w+x5cCH8AqS9ssuVOoJ4kKO8KIFuMKboagqtfJ7uEifHe5eMNAysrB8NJN4H8aevBt7SaAWLHhYmKmhjq+WBHcvRSEaKzd6Kx1HyAWoWt3thI2u9utUUHbrVZwtmEr/T9Nyz6sH9mq8ZLXUDIvk2hb2E0fK1TB2QkbFNJCR4KHhUdAeY7e40XXdfnQH8pnrEMiQ5/tONtrLh1X9FzIpeOKm6qVxr8x7JTBKOxO+yhyIbb0wVg9SD1pkBNOVvzJgu0xJ2pNH8EBtF/7Y8zJTgqO215BYSdL3KOR9qn+M3Ie6YdSvEVFDDMy4nZvIfHN0yOsCcpXCHDJjD6z53+IA/MafzKcsEdmhyr93paEbulbiD9mAep10Ks5giIe+cNU8Ydi0lRDJb5VUCAFwb6P7NSq4Y/bUdihX/0bNuzx86SQllRmBTQtiUe5HSa1++pyUQ5ZRApOeHCYz1AsaKz+byEYq5D8NoewFJZpWovQmqXFZWJuLI=
